name: Hardhat Solhint

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - '*'
jobs:
    run_hardhart_solhint:
        runs-on: ubuntu-latest
        name: Run the Hardhat solhint
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x
            - run: npm install
            - run: npx hardhat check
